// live/svelte/src/App.svelte
<script lang="ts">
  import { importIcon } from "unplugin-svg-transformer/icons";
  import SvgIcon from "./lib/SvgIcon.svelte";

  let render: string = "";
  async function getIcon(icon: IconType) {
    let svg = await importIcon(icon);
    render = svg.default;
  }
  getIcon("download");
</script>

<main>
  <span>{@html render}</span>
  <SvgIcon name={"download"} />
</main>

// live/nuxt3/app.vue
<script setup lang="ts">
// import { importIcon } from '#icons'
import { importIcon } from 'unplugin-svg-transformer/icons'

const svg = await importIcon('vite-3')
console.warn(svg.default)
</script>

<template>
  <div>
    <SvgIcon name="download" />
    <SvgIcon name="download" />
    <SvgIcon name="vite-3" />
    <SvgIcon name="vite-3" />
  </div>
</template>

<style lang="css">
svg {
  width: 3rem !important;
  height: 3rem !important;
}
</style>
