// live/svelte/src/App.svelte
<script lang="ts">
  import { importIcon } from "unplugin-svg-transformer/icons";
  import SvgIcon from "./lib/SvgIcon.svelte";

  let render: string = "";
  async function getIcon(icon: IconType) {
    let svg = await importIcon(icon);
    render = svg.default;
  }
  getIcon("download");
</script>

<main>
  <span>{@html render}</span>
  <SvgIcon name={"download"} />
</main>

// live/vue3/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { VueSvg } from 'unplugin-svg-transformer/vue'
import { importIcon } from 'unplugin-svg-transformer/icons'

const icon = ref<string>()
const importMethod = ref<string>()

function fetchIcon() {
  if (!window.importIcon)
    return

  window.importIcon('vue').then(svg => icon.value = svg.default)
  importIcon('vue').then(svg => importMethod.value = svg.default)
}
fetchIcon()
</script>

<template>
  <div>
    Vue 3
    <div v-html="icon" />
    <div v-html="importMethod" />
    <SvgIcon name="vite-copy" />
    <VueSvg name="vite-copy" />
  </div>
</template>
