// examples/vue3/src/App.vue
<script setup lang="ts">
import {VueSvg} from 'unplugin-svg-transformer/vue'
import { ref } from 'vue'

const icon = ref<string>()

async function fetchIcon() {
  icon.value = (await window.importIcon('download')).default
}
fetchIcon()
</script>

<template>
  <div>
    Vue 3
    <div v-html="icon"></div>
    <VueSvg name="vite" />
    <SvgIcon name="vite" />
  </div>
</template>

// live/svelte/src/App.svelte
<script lang="ts">
  import { importIcon } from "unplugin-svg-transformer/icons";
  import SvgIcon from "./lib/SvgIcon.svelte";

  let render: string = "";
  async function getIcon(icon: IconType) {
    let svg = await importIcon(icon);
    render = svg.default;
  }
  getIcon("download");
</script>

<main>
  <span>{@html render}</span>
  <SvgIcon name={"download"} />
</main>
